
class TwinPeakActions:
    GET_ALL_RECEIPTS = "GET_ALL_RECEIPTS"
    GET_RECEIPT_BY_ID = "GET_RECEIPT_BY_ID"
    GET_RECEIPT_ITEM_BY_ID = "GET_RECEIPT_ITEM_BY_ID"
    GET_USDA_FOOD_INFO = "GET_USDA_FOOD_INFO"
    POST_USDA_FOOD = "POST_USDA_FOOD"
    GET_USDA_FOOD_INFO_BY_UPC = "GET_USDA_FOOD_INFO_BY_UPC"
    GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"
    POST_INGREDIENT = "POST_INGREDIENT"
